export default Object.freeze({
  CMS_COMPONENTS: {
    FORM_BLOCK: 'section.form-block',
    HERO_BANNER: 'section.hero-banner',
    LOCATIONS_BLOCK: 'section.locations-block',
    PRODUCT_BLOCK: 'section.product-block',
    SERVICE_BLOCK: 'section.service-block',
    PACKAGE_BLOCK: 'section.package-block',
    FEATURE_BLOCK: 'section.feature-block',
    LIST_BLOCK: 'section.list-block',
    LETS_TALK_SECTION: 'section.lets-talk',
    OPENINGS_SECTION: 'section.openings-section',
    ACTION_COMPONENT: 'component.action',
    CLAIMS_SECTION: 'section.claims-section',
    DESCRIPTION_BLOCK: 'section.description-block',
    PARAGRAPH_BLOCK: 'component.paragraph-block',
    PEOPLE_BLOCK: 'section.people-block',
    GRID_BLOCK: 'section.grid-block',
    RICH_DISPLAY: 'component.rich-display',
    JOB_APPLICATION_SECTION: 'section.job-application-form',
    AUTO_INSURANCE_FORM: 'section.auto-insurance-form',
    TRAVEL_INSURANCE_FORM: 'section.travel-insurance-form',
  },
  ICON_CLASSNAMES: {
    COMMUNICATION_CALL: 'icon-Icons_Communication-Call-1Default',
    COMMUNICATION_EMAIL: 'icon-Icons_Communication-Email-1Default',
  },
  DEFAULTS: {
    MAP_ZOOM_LEVEL: 10,
  },
});
